WIP: Dev
ukitgroup/nestjs-config pull request #2
Opened 2020-06-27 15:17 UTC by Velmisov

2020-06-29 13:21 UTC, Goodluckhf requested changes

2020-06-29 13:21 UTC, Goodluckhf commented on e2e-test/config.e2e-spec.ts
> +          }),
Here we have to get config from object, env, ...

2020-06-29 13:21 UTC, Goodluckhf commented on e2e-test/config.e2e-spec.ts
> +      @IsInt()
If we provide convenient abstraction for configuration, it's common to validate all integers that is integer. So we can provide wrappers for decorators

We can combine 2 decorators as one E.g `Integer()`

2020-06-29 13:21 UTC, Goodluckhf commented on src/decorator.ts
> +export function ModuleConfig(name: string): (target) => void {
Just `Config` is ok imho

2020-06-29 19:08 UTC, Velmisov commented
What do you think about Global config? Do we need this?

2020-06-29 19:12 UTC, Goodluckhf commented
> What do you think about Global config? Do we need this?

What will we store there? Or what do you mean?

2020-06-29 19:23 UTC, Velmisov commented
> > What do you think about Global config? Do we need this?
> 
> What will we store there? Or what do you mean?

Someone might want to have global envs or variables that don't belong to any module. I can be wrong but NODE_ENV, etc can be used in more than one module.

As we have the ability to create Global module, so we should provide Global config too. For some needs.

2020-06-29 19:34 UTC, Goodluckhf commented
> NODE_ENV
Usually it's just env variable. I can't imagine that you have to override `NODE_ENV` in code. And actually it's more complex. This iteration I think we can satisfy our requirements without it. But in some iteration probably we will add 3d part of config depending on `NODE_ENV` (production, staging, test, dev) and somehow merge  them.

2020-06-29 20:06 UTC, Velmisov commented on e2e-test/config.e2e-spec.ts
> +          }),
What do u mean? File could be in different formats or module input here?

2020-06-29 20:07 UTC, Velmisov commented
> This iteration I think we can satisfy our requirements without it

Okay

2020-07-02 10:47 UTC, Goodluckhf requested changes

2020-07-02 10:47 UTC, Goodluckhf commented on src/core.ts
> +    throw new Error(JSON.stringify(validationErrors));
we have to provide clear errors without `JSON.stringify`
- module name
- env path
- maybe type requirements
etc...

2020-07-02 10:47 UTC, Goodluckhf commented on src/core.ts
> +import * as dotenv from 'dotenv';
It's better to name obvious, not like `core,share,lib` Here we can separate at least 3 components:
- config parsing
- config transformation
- config validation

2020-07-02 10:47 UTC, Goodluckhf commented on src/options.ts
> +  fromProcess?: boolean;
this case we can use as default behaviour

2020-07-02 10:47 UTC, Goodluckhf commented on src/module.ts
> +  static forRoot(options: ConfigOptions): DynamicModule {
don't forget to add optional dependency `Logger` for logging errors of validation/transformation

2020-07-02 10:47 UTC, Goodluckhf commented
- add test case with several configs

2020-07-02 15:39 UTC, Goodluckhf commented on src/lib/facade.ts
> +  private readonly configValidator = new ConfigValidator();
where is DI?🧐

2020-07-08 14:48 UTC, Goodluckhf requested changes

2020-07-08 14:48 UTC, Goodluckhf commented on src/lib/global-module.ts
> +        useValue: console,
it's bad idea to use `console` as a logger. If there is no logger in providers we just don't logging it

2020-07-08 14:48 UTC, Goodluckhf commented on src/lib/global-module.ts
> +        useValue: console,
we can create a wrapper provider that depends on this logger. And there decide log or not. It will help us not to change `this.logger....`

2020-07-08 15:42 UTC, Velmisov commented on src/options.ts
> +export type ConfigOptions = {
We should provide ability to add raw config

2020-07-10 05:36 UTC, Goodluckhf approved these changes

2020-07-10 12:45 UTC, merged

2020-07-10 13:06 UTC, Goodluckhf commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ukitgroup/nestjs-config/v/1.0.0)
- [GitHub release](https://github.com/ukitgroup/nestjs-config/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: